package com.archis.utils;

import lombok.Getter;

@Getter
public enum ZoneEnum {
    PLANTALA("Plantala"),
    TOMBEAUX("Mont des Tombeaux"),
    BOO("Coin des Boos"),
    FEUDALA("Feudala"),
    GROBE("Cimetière de Grobe"),
    MARECAGES_NAU("Marécages nausébonds"),
    MARECAGES_AMAKNA("Marécages d'Amakna"),
    MARECAGES_FOND("Marécages sans fond"),
    HAKAM_FEUILLAGE("Feuillage de l'arbre Hakam"),
    CANIA_LAC("Lac de Cania"),
    HAKAM_TRONC("Tronc de l'arbre Hakam"),
    FUNGUS_CAVERNE("Caverne des Fungus"),
    CAMPEMENT_GOBELINS("Campement des Gobelins"),
    BOIS_LITNEG("Bois de Litneg"),
    CANOPEE_VILLAGE("Village de la Canopée"),
    ZOTH_VILLAGE("Village des Zoths"),
    ASTRUB_EGOUTS("Égouts d'Astrub"),
    CHEMIN_CRANE("Chemin du Crâne"),
    TAINELA("Tainéla"),
    TOURBIERE_SANS_FOND("Tourbière sans fond"),
    TOURBIERE_NAUSEABONDE("Tourbière nauséabonde"),
    PLAINE_PORKASS("Plaine des Porkass"),
    CLAIRIERE_BROUCE("Clairière de Brouce Boulgoure"),
    DESOLATION_SIDIMOTE("Désolation de Sidimote"),
    AERDALA("Aerdala"),
    CIMETIERE("Cimetière"),
    BWORK_CAMPEMENT("Campement des Bworks"),
    VALLEE_MORKHITU("Vallée de la Morh'Kitu"),
    COIN_BOUFTOUS("Coin des Bouftous"),
    MONTAGNE_BASSE_CRAQUELEURS("Montagne basse des Craqueleurs"),
    CANYON_SAUVAGE("Canyon sauvage"),
    FORET_MALEFIQUE("Forêt maléfique"),
    VILLAGE_DOPEULS("Village des Dopeuls"),
    MINE_DOPEULS("Mine des Dopeuls"),
    OREE_ABRAKNYDE("Orée de la forêt des Abraknydes"),
    FORET_SOMBRE("Forêt sombre"),
    JUNGLE_OBSCURE("Jungle obscure"),
    AKWADALA("Akwadala"),
    DENTS_DE_PIERRE("Dents de pierre"),
    VILLAGE_KANIGS("Village des Kanigs"),
    BAIE_CANIA("Baie de Cania"),
    SOUTERRAINS_ASTRUB("Souterrains d'Astrub"),
    CAMPAGNE_AMAKNA("Campagne d'Amakna"),
    PASSAGE_BRAKMAR("Passage vers Brâkmar"),
    TERRITOIRE_BANDITS("Territoire des Bandits"),
    VILLAGE_BWORKS("Village des Bworks"),
    ARCHE_OTOMAI("Arche d'Otomaï"),
    TERRDALA("Terrdala"),
    CHAMPS_CANIA("Champs de Cania"),
    CIMETIERE_HEROS("Cimetière des Héros"),
    CIMETIERE_TORTURES("Cimetière des Torturés"),
    DOMAINE_FUNGUS("Domaine des Fungus"),
    SOUTERRAINS_CHATEAU("Souterrains du Château d'Amakna"),
    PLAGE_CORAIL("Plage de Corail"),
    MONTAGNE_CRAQUELEURS("Montagne des Craqueleurs"),
    PLAINES_ROCHEUSES("Plaines rocheuses"),
    PLAINES_HERBEUSES("Plaines herbeuses"),
    RIVAGE_SUFOKIEN("Rivage sufokien"),
    LACS_ENCHANTES("Lacs enchantés"),
    FORET_KALIPTUS("Forêt de Kaliptus"),
    ANTRE_KOULOSSE("Antre du Koulosse"),
    SANCTUAIRE_DRAGOEUF("Sanctuaire des Dragoeufs"),
    VILLAGE_DRAGOEUF("Village des Dragoeufs"),
    SOUTERRAIN_DRAGOEUF("Souterrain des Dragoeufs"),
    PRESQUILE_DRAGOEUF("Presqu'île des Dragoeufs"),
    TERRITOIRE_DRAGODINDES("Territoire des Dragodindes Sauvages"),
    BORDURE_BRAKMAR("Bordure de Brâkmar"),
    LABYRINTHE_DRAGON_COCHON("Labyrinthe du Dragon Cochon"),
    TERRITOIRE_PORCOS("Territoire des Porcos"),
    CIMETIERE_PRIMITIF("Cimetière Primitif"),
    ROUTES_ROCAILLEUSES("Routes rocailleuses"),
    JUNGLE_INTERDITE("Jungle interdite"),
    CIMETIERE_ASTRUB("Cimetière d'Astrub"),
    PENINSULE_GELEES("Péninsule des Gelées"),
    LABYRINTHE_MINOTOROR("Labyrinthe du Minotoror"),
    ILOT_COURONNE("Îlot de la Couronne"),
    ILOT_WALDO("Îlot de Waldo"),
    FORET_MASQUES("Forêt des Masques"),
    PLAGE_TORTUE("Plage de la Tortue"),
    ILE_NAUFRAGES("Île des Naufragés"),
    ILE_MINOTOROR("Île du Minotoror"),
    PRAIRIES_ASTRUB("Prairies d'Astrub"),
    PORT_MADRESTAM("Port de Madrestam"),
    BORD_FORET_MALEFIQUE("Bord de la forêt maléfique"),
    COTE_ASSE("Côte d'Asse"),
    RIVIERE_KAWAII("Rivière Kawaii"),
    CRYPTES_CIMETIERE("Cryptes du cimetière"),
    MASSIF_CANIA("Massif de Cania"),
    FORET_ASTRUB("Forêt d'Astrub"),
    FORET_AMAKNA("Forêt d'Amakna"),
    MILLIFUTAIE("Millifutaie"),
    HAUTS_HURLEMENTS("Hauts des Hurlements"),
    CALANQUES_ASTRUB("Calanques d'Astrub"),
    SUFOKIA("Sufokia"),
    VILLAGE_AMAKNA("Village d'Amakna"),
    CITE_ASTRUB("Cité d'Astrub"),
    FAUBOURGS_ARTISANTS("Faubourgs des Artisants"),
    HAVRES_IVOIRE("Havres d'Ivoire"),
    COEUR_IMMACULE("Coeur Immaculé"),
    PROMONTOIRE_CIEUX("Promontoire des Cieux"),
    CUIRASSE("La Cuirasse"),
    ANCRE("L'Ancre"),
    MARMITE("La Marmite"),
    ENCLUME("L'Enclume"),
    RIVES_IRIDISCENTES("Rives Iridiscentes"),
    CHAMPS_ASTRUB("Champs d'Astrub"),
    PLAINE_SCARAFEUILLES("Plaine des Scarafeuilles"),
    ILE_CAWOTTE("Île de la Cawotte"),
    CHAMP_INGALSSE("Champ des Ingalsse"),
    ILOT_TOMBEAUX("Îlot des Tombeaux");


    private String nom;
    ZoneEnum(String nom) {
        this.nom = nom;
    }

    public static ZoneEnum getZoneEnum(String nom) {
        for (ZoneEnum zone : ZoneEnum.values()) {
            if (zone.getNom().toLowerCase().equals(nom.toLowerCase())) {
                return zone;
            }
        }
        return null;
    }
}
